# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nu_k_root_finder_equation_cpp <- function(data, p, z_k, n_k, nu_k, Sigma_inv_k, N) {
    .Call(`_sparsemixwishart_nu_k_root_finder_equation_cpp`, data, p, z_k, n_k, nu_k, Sigma_inv_k, N)
}

